services:
  client:
    container_name: client
    init: true
    image: ${ECR_AWS_ACCOUNT_ID}.dkr.ecr.${ECR_AWS_REGION}.amazonaws.com/${ECR_CLIENT_IMAGE_TAG}
    networks:
      - hydroshift
    restart: unless-stopped
    mem_limit: 4GB
    mem_reservation: 2GB

networks:
  hydroshift:
    driver: bridge
