name: Main Branch Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'hydroshift/**'
      - 'tests/**'
      - '.devcontainer/Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'
      - 'pyproject.toml'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  get-version:
    name: Extract Package Version
    uses: ./.github/workflows/get-version.yaml

  check-version-exists:
    name: Verify Version is New
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Fail if version already exists
        if: needs.get-version.outputs.is_new_version != 'true'
        run: |
          echo "::error::ERROR: Version ${{ needs.get-version.outputs.version }} already exists as a tag."
          echo "::error::Please update the version in hydroshift/__init__.py before releasing to main."
          exit 1
      - name: Version check passed
        run: echo "Version ${{ needs.get-version.outputs.version }} is new. Proceeding with release."

  docker-build-push:
    name: Build and Push Docker Image
    needs: [get-version, check-version-exists]
    uses: ./.github/workflows/docker-build.yaml
    with:
      push_to_registry: true
      version: ${{ needs.get-version.outputs.version }}
      branch: 'main'
      platforms: 'linux/amd64'
    secrets: inherit
